[package]
name = "locutus-runtime"
version = "0.0.1"
edition = "2021"
rust-version = "1.58.0"
resolver = "2"

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
blake2 = { version =  "0.10", features = [ "std" ] }
hex = "0.4"
serde = { version = "1", features = ["rc", "derive"] }
thiserror = "1"
wasmer = { version = "^2.0", default-features = false }

[features]
default = [ "wasmer-default" ]
wasmer-default = [ "wasmer/sys-default" ]
