[package]
name = "locutus-node"
version = "0.0.1"
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "node-deploy" 
path = "src/bin/gateway-deploy.rs"
doc = false

[dependencies]
# anyhow = "1.0.42"
async-trait = "0.1.51"
bincode = "1.3"
config = { version = "0.11", features = [ "toml" ] } 
crossbeam = "0.8.1"
env_logger = "0.9.0"
futures = "0.3.17"
libp2p = { version = "0.39", features = [
    "identify",
    "mplex",
    "noise",
    "tcp-tokio",
    "dns-tokio",
    "yamux"
] }
log = { version = "0.4", features = ["serde"] }
once_cell = "1.8"
parking_lot = "0.11.2"
rand = "0.8"
rust-fsm = "0.6.0"
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1.10", features = ["rt-multi-thread", "sync", "macros"] }
typestate = "0.8.0"
uuid = { version = "0.8", features = ["serde", "v4", "v5"] }
